# Jekyll Configuration

# General
title:       Creating Interactive Maps with D3
author:      Pablo Navarro Castillo
email:       pnavarrc@gmail.com

# Paths
destination: ./dist
baseurl:     /d3-creating-interactive-maps/dist

# Build Settings
safe:        true
markdown:    kramdown
permalink:   pretty
